name: Cron

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.NETLIFY_CRON_BUILD_HOOK }}
          data: ""
